export enum TranslationsValues {
	title_home = 'title_home',
	button_label_home = 'button_label_home',
	name_required = 'name_required',
	board_required = 'board_required',
	value_required = 'value_required',
	add_name_truck_label = 'add_name_truck_label',
	add_board_truck_label = 'add_board_truck_label',
	cancel = 'cancel',
	add = 'add',
	save = 'save',
	delete = 'delete',
	edit = 'edit',
	close = 'close',
	add_truck_header_title = 'add_truck_header_title',
	history = 'history',
	trucks = 'trucks',
	title_truck = 'title_truck',
	shipping = 'shipping',
	diesel = 'diesel',
	maintenance = 'maintenance',
	tire = 'tire',
	tracking = 'tracking',
	salary = 'salary',
	admExpenses = 'admExpenses',
	parcels = 'parcels',
	taxes = 'taxes',
	insurance = 'insurance',
	accountant = 'accountant',
	advance = 'advance',
	toll = 'toll',
	restaurant = 'restaurant',
	others = 'others',
	toast_add_truck = 'toast_add_truck',
	toast_edit_truck = 'toast_edit_truck',
	toast_delete_truck = 'toast_delete_truck',
	toast_add_option = 'toast_add_option',
	edit_truck_name_label = 'edit_truck_name_label',
	edit_truck_board_label = 'edit_truck_board_label',
	editing_truck_title = 'editing_truck_title',
	empty_trucks = 'empty_trucks',
	delete_truck_warning = 'delete_truck_warning',
	delete_truck_warning2 = 'delete_truck_warning2',
	add_option_value_label = 'add_option_value_label',
	add_option_description_label = 'add_option_description_label',
	empty_description = 'empty_description',
	review_title = 'review_title',
	value = 'value',
	description = 'description',
	empty_timeline = 'empty_timeline',
	total_gains = 'total_gains',
	total_costs = 'total_costs',
	subtotal = 'subtotal',
	empty_month = 'empty_month',
	toast_edit_option = 'toast_edit_option',
	toast_delete_option = 'toast_delete_option',
	edit_option_value_label = 'edit_option_value_label',
	edit_option_description_label = 'edit_option_description_label',
	edit_option_title = 'edit_option_title',
	delete_option_title = 'delete_option_title',
	language = 'language',
}

export const translations = {
	en: {
		title_home: 'Added Trucks',
		button_label_home: 'Tap here to add a truck',
		name_required: 'The name is required',
		board_required: 'The board is required',
		value_required: 'The value is required',
		add_name_truck_label: 'Add a name for the truck',
		add_board_truck_label: 'Add a board for the truck',
		cancel: 'Cancel',
		add: 'Add',
		edit: 'Edit',
		save: 'Save',
		delete: 'Delete',
		close: 'Close',
		add_truck_header_title: 'Add Truck',
		history: 'History',
		trucks: 'Trucks',
		title_truck: 'Choose which option you want to add to accounting',
		shipping: 'Shipping',
		diesel: 'Diesel',
		maintenance: 'Maintenance',
		tire: 'Tire',
		tracking: 'Tracking',
		salary: 'Salary',
		admExpenses: 'Administrative Costs',
		parcels: 'Parcels',
		taxes: 'Taxes',
		insurance: 'Insurance',
		accountant: 'Accounting Advice',
		advance: 'Advance',
		toll: 'Toll',
		restaurant: 'Restaurant',
		others: 'Others',
		toast_add_truck: '{{name}}/{{board}} truck has been added',
		toast_edit_truck: 'Truck {{name}}/{{board}} has been edited',
		toast_delete_truck: 'Truck {{name}}/{{board}} has been deleted',
		edit_truck_name_label: 'Edit truck name',
		edit_truck_board_label: 'Edit truck board',
		editing_truck_title: 'You are editing the truck',
		empty_trucks: "You haven't added a truck yet",
		delete_truck_warning: 'You are about to delete the truck',
		delete_truck_warning2:
			'All records for that truck will be deleted. Are you sure about that?',
		toast_add_option: 'You have registered a value in %{value}',
		add_option_value_label: 'Add a value for this option',
		add_option_description_label: 'Add a description for this value',
		empty_description: 'No description added',
		review_title: 'Please check that the values are correct before adding',
		value: 'Value',
		description: 'Description',
		empty_timeline: "You haven't added any value yet",
		total_gains: 'Total earnings for {{value}} ',
		total_costs: 'Total costs for {{value}}',
		subtotal: 'Subtotal',
		empty_month: "You haven't registered any value this month",
		toast_edit_option: 'A {{value}} option has been updated',
		toast_delete_option: 'A {{value}} option was deleted',
		edit_option_value_label: 'Edit the value for this option',
		edit_option_description_label: 'Edit the description for this value',
		edit_option_title: 'You are editing a record for {{value}}',
		delete_option_title:
			'You are about to delete this record. Are you sure about that?',
		language: 'Language',
	},
	pt: {
		title_home: 'Caminhões adicionados',
		button_label_home: 'Toque aqui para adiconar um caminhão',
		name_required: 'O nome é obrigatório',
		board_required: 'A placa é obrigatória',
		value_required: 'O valor é obrigatório',
		add_name_truck_label: 'Adicionar um nome para o caminhão',
		add_board_truck_label: 'Adicionar a placa do caminhão',
		cancel: 'Cancelar',
		add: 'Adicionar',
		save: 'Salvar',
		edit: 'Editar',
		delete: 'Excluir',
		close: 'Fechar',
		add_truck_header_title: 'Adiconar Caminhão',
		history: 'Histórico',
		trucks: 'Caminhões',
		title_truck: 'Escolha qual opção deseja adicionar à contabilidade',
		shipping: 'Frete',
		diesel: 'Diesel',
		maintenance: 'Manutenção',
		tire: 'Pneu',
		tracking: 'Rastreamento',
		salary: 'Salário',
		admExpenses: 'Despesas Administrativas',
		parcels: 'Parcelas',
		taxes: 'Tributos',
		insurance: 'Seguro',
		accountant: 'Assessoria Contábil',
		advance: 'Adiantamento',
		toll: 'Pedágio',
		restaurant: 'Restaurante',
		others: 'Outros',
		toast_add_truck: 'O caminhão {{name}}/{{board}} foi adicionado',
		toast_edit_truck: 'O caminhão {{name}}/{{board}} foi editado',
		toast_delete_truck: 'O caminhão {{name}}/{{board}} foi excluido',
		edit_truck_name_label: 'Editar o nome do caminhão',
		edit_truck_board_label: 'Editar a placa do caminhão',
		editing_truck_title: 'Você está editando o caminhão',
		empty_trucks: 'Você ainda não adicinou um caminhão',
		delete_truck_warning: 'Você está prestes a excluir o caminhão',
		delete_truck_warning2:
			'Todos registros desse caminhão serão apagados. Tem certeza disso?',
		toast_add_option: 'Você registrou um valor em {{value}}',
		add_option_value_label: 'Adicione um valor para essa opção',
		add_option_description_label: 'Adicione uma descrição para esse valor',
		empty_description: 'Nenhuma descrição adicionada',
		review_title:
			'Por favor, revise se os valores estão corretos antes de adicionar',
		value: 'Valor',
		description: 'Descrição',
		empty_timeline: 'Você não adicionou nenhum valor ainda',
		total_gains: 'Total de ganhos de {{value}}',
		total_costs: 'Total de custos de {{value}}',
		subtotal: 'Subtotal',
		empty_month: 'Você não registrou nenhum valor nesse mês',
		toast_edit_option: 'Uma opção {{value}} foi atualizada',
		toast_delete_option: 'Uma opção {{value}} foi excluida',
		edit_option_value_label: 'Editar o valor para essa opção',
		edit_option_description_label: 'Editar a descrição para esse valor',
		edit_option_title: 'Você está editando um registro para {{value}}',
		delete_option_title:
			'Você está prestes a excluir este registro. Tem certeza disso?',
		language: 'Idioma',
	},
};
