export enum TranslationsValues {
	title_home = 'title_home',
	button_label_home = 'button_label_home',
	name_required = 'name_required',
	board_required = 'board_required',
	value_required = 'value_required',
	add_name_truck_label = 'add_name_truck_label',
	add_board_truck_label = 'add_board_truck_label',
	cancel = 'cancel',
	add = 'add',
	save = 'save',
	delete = 'delete',
	edit = 'edit',
	close = 'close',
	continue = 'continue',
	add_truck_header_title = 'add_truck_header_title',
	history = 'history',
	trucks = 'trucks',
	title_truck = 'title_truck',
	shipping = 'shipping',
	shipping_description = 'shipping_description',
	diesel = 'diesel',
	diesel_description = 'diesel_description',
	maintenance = 'maintenance',
	maintenance_description = 'maintenance_description',
	tire = 'tire',
	tire_description = 'tire_description',
	tracking = 'tracking',
	tracking_description = 'tracking_description',
	salary = 'salary',
	salary_description = 'salary_description',
	admExpenses = 'admExpenses',
	admExpenses_description = 'admExpenses_description',
	parcels = 'parcels',
	parcels_description = 'parcels_description',
	taxes = 'taxes',
	taxes_description = 'taxes_description',
	insurance = 'insurance',
	insurance_description = 'insurance_description',
	accountant = 'accountant',
	accountant_description = 'accountant_description',
	advance = 'advance',
	advance_description = 'advance_description',
	toll = 'toll',
	toll_description = 'toll_description',
	restaurant = 'restaurant',
	restaurant_description = 'restaurant_description',
	others = 'others',
	others_description = 'others_description',
	toast_add_truck = 'toast_add_truck',
	toast_edit_truck = 'toast_edit_truck',
	toast_delete_truck = 'toast_delete_truck',
	toast_add_option = 'toast_add_option',
	edit_truck_name_label = 'edit_truck_name_label',
	edit_truck_board_label = 'edit_truck_board_label',
	editing_truck_title = 'editing_truck_title',
	empty_trucks = 'empty_trucks',
	delete_truck_warning = 'delete_truck_warning',
	delete_truck_warning2 = 'delete_truck_warning2',
	add_option_value_label = 'add_option_value_label',
	add_option_description_label = 'add_option_description_label',
	empty_description = 'empty_description',
	review_title = 'review_title',
	value = 'value',
	description = 'description',
	empty_timeline = 'empty_timeline',
	total_gains = 'total_gains',
	total_costs = 'total_costs',
	subtotal = 'subtotal',
	empty_month = 'empty_month',
	toast_edit_option = 'toast_edit_option',
	toast_delete_option = 'toast_delete_option',
	edit_option_value_label = 'edit_option_value_label',
	edit_option_description_label = 'edit_option_description_label',
	edit_option_title = 'edit_option_title',
	delete_option_title = 'delete_option_title',
	language = 'language',
	theme = 'theme',
	download = 'download',
	share = 'share',
	toast_download = 'toast_download',
	toast_download_year = 'toast_download_year',
	push_content = 'push_content',
	welcome = 'welcome',
	use_term = 'use_term',
	welcome_paragraph = 'welcome_paragraph',
	enjoy = 'enjoy',
	term_checkbox_label = 'term_checkbox_label',
	modal_terms_title = 'modal_terms_title',
	network_offline = 'network_offline',
	network_error = 'network_error',
	help = 'help',
	subscribe_monthly = 'subscribe_monthly',
	subscribe_yearly = 'subscribe_yearly',
	unsubscribe = 'unsubscribe',
	donate = 'donate',
	thanks = 'thanks',
	congrats = 'congrats',
	upgrade_message = 'upgrade_message',
	upgrade_feature1 = 'upgrade_feature1',
	upgrade_feature2 = 'upgrade_feature2',
	upgrade_feature3 = 'upgrade_feature3',
	upgrade_feature4 = 'upgrade_feature4',
	upgrade_title = 'upgrade_title',
	upgrade_description = 'upgrade_description',
	warning = 'warning',
	connection_message = 'connection_message',
	network_warning = 'network_warning',
	play_store_warning = 'play_store_warning',
	apple_store_warning = 'apple_store_warning',
	attention = 'attention',
	offline_message = 'offline_message',
}

export const translations = {
	en: {
		title_home: 'Added Trucks',
		button_label_home: 'Tap here to add a truck',
		name_required: 'The name is required',
		board_required: 'The board is required',
		value_required: 'The value is required',
		add_name_truck_label: 'Add a name for the truck',
		add_board_truck_label: 'Add a board for the truck',
		cancel: 'Cancel',
		add: 'Add',
		edit: 'Edit',
		save: 'Save',
		delete: 'Delete',
		close: 'Close',
		continue: 'Next',
		add_truck_header_title: 'Add Truck',
		history: 'History',
		trucks: 'Trucks',
		title_truck: 'Choose which option you want to add to accounting',
		shipping: 'Shipping',
		shipping_description:
			'Add here all earnings related to freight received in the current month. \n This is the only option that will count a positive value.\n You can add as many times as you like, adding will record the day and time you registered this value.',
		diesel: 'Diesel',
		diesel_description:
			'Add here the vehicle fueling costs for the current month.\n You can add as many times as you like, when adding will be registered day and time that you registered this value.',
		maintenance: 'Maintenance',
		maintenance_description:
			'Add here the maintenance costs that you received from the vehicle in the current month.\n You can add as many times as you want, when adding will be registered day and time that you registered this value.',
		tire: 'Tire',
		tire_description:
			'Add here the costs with the purchase or retreading of tires in the current month.\n You can add as many times as you like, adding will be recorded the day and time you registered this amount.',
		tracking: 'Tracking',
		tracking_description:
			'Add here the costs with equipment and vehicle tracking programs in the current month.\n You can add as many times as you like, adding will record the date and time you registered this amount.',
		salary: 'Salary',
		salary_description:
			"Add here the driver's salary, own pro-labor or how much is withdrawn for own salary in the current month. \n You can add as many times as you like, adding will record the day and time you registered this value.",
		admExpenses: 'Administrative Costs',
		admExpenses_description:
			'Add here the costs of maintenance of the company, eg telephone, internet, agency and other necessary in the current month. \n You can add as many times as you like, adding will record the day and time you registered this value.',
		parcels: 'Parcels',
		parcels_description:
			'Add the monthly payment installments for the vehicle, if any, or any other bills you have here. \n You can add as many times as you like, adding will record the day and time you registered this value.',
		taxes: 'Taxes',
		taxes_description:
			'Add here the taxes/tributps payable in the current month. \n You can add as many times as you like, adding will record the day and time you registered this value.',
		insurance: 'Insurance',
		insurance_description:
			'Add here all forms of vehicle or personal insurance, eg property insurance, life insurance and transport insurance. \n You can add as many times as you like, adding will record the day and time you registered this value.',
		accountant: 'Accounting Advice',
		accountant_description:
			'Add the monthly accountant expenses here. \n You can add as many times as you like, adding will record the day and time you registered this value.',
		advance: 'Advance',
		advance_description:
			'Add here all advances payable in the current month. \n You can add as many times as you like, adding will record the day and time you registered this value.',
		toll: 'Toll',
		toll_description:
			'Add here the toll costs for the current month.\n You can add as many times as you like, when adding the date and time you registered this amount will be registered',
		restaurant: 'Restaurant',
		restaurant_description:
			'Add the food costs for the current month here. \n You can add as many times as you like, adding will record the day and time you registered this value.',
		others: 'Others',
		others_description:
			'Add here all costs calculated in the current month and that are not included in the other expense fields. \n You can add as many times as you like, adding will record the day and time you registered this value. \n You can add as many times as you like, adding will record the day and time you registered this value.',
		toast_add_truck: '{{name}}/{{board}} truck has been added',
		toast_edit_truck: 'Truck {{name}}/{{board}} has been edited',
		toast_delete_truck: 'Truck {{name}}/{{board}} has been deleted',
		edit_truck_name_label: 'Edit truck name',
		edit_truck_board_label: 'Edit truck board',
		editing_truck_title: 'You are editing the truck',
		empty_trucks: "You haven't added a truck yet",
		delete_truck_warning: 'You are about to delete the truck',
		delete_truck_warning2:
			'All records for that truck will be deleted. Are you sure about that?',
		toast_add_option: 'You have registered a value in {{value}}',
		add_option_value_label: 'Add a value for this option',
		add_option_description_label: 'Add a description for this value',
		empty_description: 'No description added',
		review_title: 'Please check that the values are correct before adding',
		value: 'Value',
		description: 'Description',
		empty_timeline: "You haven't added any value yet",
		total_gains: 'Total earnings for {{value}} ',
		total_costs: 'Total costs for {{value}}',
		subtotal: 'Subtotal',
		empty_month: "You haven't registered any value this month",
		toast_edit_option: 'A {{value}} option has been updated',
		toast_delete_option: 'A {{value}} option was deleted',
		edit_option_value_label: 'Edit the value for this option',
		edit_option_description_label: 'Edit the description for this value',
		edit_option_title: 'You are editing a record for {{value}}',
		delete_option_title:
			'You are about to delete this record. Are you sure about that?',
		language: 'Language',
		theme: 'Theme',
		download: 'Download',
		share: 'Share',
		toast_download:
			'The records for the month of {{month}} was downloaded from Documents > FinTruck',
		toast_download_year:
			'The year {{year}} records were downloaded from Documents > FinTruck',
		push_content:
			"Don't be in the red, remember to save your earnings and expenses to be able to better manage your truck :)",
		welcome: 'Welcome',
		use_term: 'Terms of Use',
		welcome_paragraph:
			'Thank you for using our app, we hope you enjoy it and that it will be very useful for you.\n Please read the ',
		enjoy: 'Enjoy!',
		term_checkbox_label: 'I read and accept the terms',
		modal_terms_title: 'Fin Truck Terms of Use',
		network_offline:
			'You are offline, you must be logged in to make a purchase',
		network_error: 'Error checking connection',
		help: 'I Need Your Help',
		donate: 'Donate',
		thanks: 'We received your donation. \nThank you so much!',
		upgrade_message:
			'You have just purchased the Premium plan. \n All features of this app in the Premium plan are accessible.',
		congrats: 'Congratulations',
		upgrade_feature1: 'Add more than one truck',
		upgrade_feature2: 'Share monthly records',
		upgrade_feature3: 'Share annual records',
		upgrade_feature4: 'No ads, except commercial partnerships.',
		upgrade_title: 'Upgrade your account',
		upgrade_description:
			'Have all the functionality of the Fin Truck app unlocked. By subscribing you will have 7 days free to try and you can cancel whenever you want.',
		subscribe_monthly: 'Subscribe monthly plan',
		subscribe_yearly: 'Subscribe annual plan',
		unsubscribe: 'Unsubscribe',
		warning: 'Warning',
		connection_message:
			'Hello friend, you are currently using the Fin Truck app on the Fremium plan. \n In this plan the use of the application is limited. To proceed you need to subscribe to our application, the value is symbolic, so you help us to maintain and improve our service. \n Please check that:',
		network_warning: 'Has internet connection',
		play_store_warning: 'You are connected to PlayStore',
		apple_store_warning: 'Is connected to the AppleStore',
		attention: 'Attention',
		offline_message:
			'The Fin Truck app works offline, you only need to be logged in to subscribe and upgrade to the Premium plan.',
	},
	pt: {
		title_home: 'Caminhões adicionados',
		button_label_home: 'Toque aqui para adiconar um caminhão',
		name_required: 'O nome é obrigatório',
		board_required: 'A placa é obrigatória',
		value_required: 'O valor é obrigatório',
		add_name_truck_label: 'Adicionar um nome para o caminhão',
		add_board_truck_label: 'Adicionar a placa do caminhão',
		cancel: 'Cancelar',
		add: 'Adicionar',
		save: 'Salvar',
		edit: 'Editar',
		delete: 'Excluir',
		close: 'Fechar',
		continue: 'Continuar',
		add_truck_header_title: 'Adiconar Caminhão',
		history: 'Histórico',
		trucks: 'Caminhões',
		title_truck: 'Escolha qual opção deseja adicionar à contabilidade',
		shipping: 'Frete',
		shipping_description:
			'Adicione aqui todos os ganhos relativos à fretes recebidos no mês vigente.\n Esta é a única opção que contabilizará um valor positivo.\n Você pode adicionar quantas vezes quiser, ao adicionar será registrado dia e hora que você registrou esse valor.',
		diesel: 'Diesel',
		diesel_description:
			'Adicione aqui, os custos com abastecimento do veículo no mês vigente.\n Você pode adicionar quantas vezes quiser, ao adicionar será registrado dia e hora que você registrou esse valor.',
		maintenance: 'Manutenção',
		maintenance_description:
			'Adicione aqui, os custos com manutenções que você obeteve do veículo no mês vigente.\n Você pode adicionar quantas vezes quiser, ao adicionar será registrado dia e hora que você registrou esse valor.',
		tire: 'Pneu',
		tire_description:
			'Adicione aqui, os custos com compra ou reforma de pneus no mês vigente.\n Você pode adicionar quantas vezes quiser, ao adicionar será registrado dia e hora que você registrou esse valor.',
		tracking: 'Rastreamento',
		tracking_description:
			'Adicione aqui, os custos com equipamentos e programas de rastreamento do veículo no mês vigente.\n Você pode adicionar quantas vezes quiser, ao adicionar será registrado dia e hora que você registrou esse valor.',
		salary: 'Salário',
		salary_description:
			'Adicione aqui, o salário do motorista, pró-labore próprio ou quanto é retirado para salário próprio no mês vigente. \n Você pode adicionar quantas vezes quiser, ao adicionar será registrado dia e hora que você registrou esse valor.',
		admExpenses: 'Despesas Administrativas',
		admExpenses_description:
			'Adicione aqui os custos com manutenção da empresa, ex: telefone, internet, agenciamento e outros necessários no mês vigente. \n Você pode adicionar quantas vezes quiser, ao adicionar será registrado dia e hora que você registrou esse valor.',
		parcels: 'Parcelas',
		parcels_description:
			'Adicione aqui as parcelas mensais de pagamento do veículo, se houver, ou de quaisquer outras contas que você pussuir. \n Você pode adicionar quantas vezes quiser, ao adicionar será registrado dia e hora que você registrou esse valor.',
		taxes: 'Tributos',
		taxes_description:
			'Adicione aqui, os impostos/tributos a pagar no mês vigente. \n Você pode adicionar quantas vezes quiser, ao adicionar será registrado dia e hora que você registrou esse valor',
		insurance: 'Seguro',
		insurance_description:
			'Adicione aqui, todas as formas de seguro do veículo ou pessoal, ex: seguros patrimoniais, seguros de vida e seguros de transporte. \n Você pode adicionar quantas vezes quiser, ao adicionar será registrado dia e hora que você registrou esse valor',
		accountant: 'Assessoria Contábil',
		accountant_description:
			'Adicione aqui as despesas mensais com contador. \n Você pode adicionar quantas vezes quiser, ao adicionar será registrado dia e hora que você registrou esse valor',
		advance: 'Adiantamento',
		advance_description:
			'Adicione aqui todos os adiantamentos a pagar no mês vigente. \n Você pode adicionar quantas vezes quiser, ao adicionar será registrado dia e hora que você registrou esse valor ',
		toll: 'Pedágio',
		toll_description:
			'Adicione aqui, os custos com pedágio no mês vigente.\n Você pode adicionar quantas vezes quiser, ao adicionar será registrado dia e hora que você registrou esse valor ',
		restaurant: 'Restaurante',
		restaurant_description:
			'Adicione aqui, os custos com alimentação durante o mês vigente. \n Você pode adicionar quantas vezes quiser, ao adicionar será registrado dia e hora que você registrou esse valor. \n Você pode adicionar quantas vezes quiser, ao adicionar será registrado dia e hora que você registrou esse valor',
		others: 'Outros',
		others_description:
			'Adicione aqui, todos custos apurados no mês vigente e que não estão incluídos nos outros campos de despesas. \n Você pode adicionar quantas vezes quiser, ao adicionar será registrado dia e hora que você registrou esse valor. \n Você pode adicionar quantas vezes quiser, ao adicionar será registrado dia e hora que você registrou esse valor',
		toast_add_truck: 'O caminhão {{name}}/{{board}} foi adicionado',
		toast_edit_truck: 'O caminhão {{name}}/{{board}} foi editado',
		toast_delete_truck: 'O caminhão {{name}}/{{board}} foi excluido',
		edit_truck_name_label: 'Editar o nome do caminhão',
		edit_truck_board_label: 'Editar a placa do caminhão',
		editing_truck_title: 'Você está editando o caminhão',
		empty_trucks: 'Você ainda não adicinou um caminhão',
		delete_truck_warning: 'Você está prestes a excluir o caminhão',
		delete_truck_warning2:
			'Todos registros desse caminhão serão apagados. Tem certeza disso?',
		toast_add_option: 'Você registrou um valor em {{value}}',
		add_option_value_label: 'Adicione um valor para essa opção',
		add_option_description_label: 'Adicione uma descrição para esse valor',
		empty_description: 'Nenhuma descrição adicionada',
		review_title:
			'Por favor, revise se os valores estão corretos antes de adicionar',
		value: 'Valor',
		description: 'Descrição',
		empty_timeline: 'Você não adicionou nenhum valor ainda',
		total_gains: 'Total de ganhos de {{value}}',
		total_costs: 'Total de custos de {{value}}',
		subtotal: 'Subtotal',
		empty_month: 'Você não registrou nenhum valor nesse mês',
		toast_edit_option: 'Uma opção {{value}} foi atualizada',
		toast_delete_option: 'Uma opção {{value}} foi excluida',
		edit_option_value_label: 'Editar o valor para essa opção',
		edit_option_description_label: 'Editar a descrição para esse valor',
		edit_option_title: 'Você está editando um registro para {{value}}',
		delete_option_title:
			'Você está prestes a excluir este registro. Tem certeza disso?',
		language: 'Idioma',
		theme: 'Tema',
		download: 'Baixar',
		share: 'Compartilhar',
		toast_download:
			'Os registros do mês de {{month}} foi baixado em Documentos > FinTruck',
		toast_download_year:
			'Os registros do ano {{year}} foi baixado em Documentos > FinTruck',
		push_content:
			'Não fique no vermelho, lembre-se de salvar seus ganhos e gastos para poder gerenciar melhor seu caminhão :)',
		welcome: 'Seja Bem Vindo',
		use_term: 'Termo de Uso',
		welcome_paragraph:
			'Obrigado por usar nosso aplicativo, esparamos que goste e que seja muito util para você.\n Por favor, antes de continuar leia nosso',
		enjoy: 'Aproveite!',
		term_checkbox_label: 'Li e aceito os termos de uso',
		modal_terms_title: 'Termo de Uso Fin Truck',
		network_offline:
			'Você está offline, é necessário estar conectado para realizar uma compra',
		network_error: 'Error ao verificar conexão',
		help: 'Eu Preciso Da Sua Ajuda',
		buy: 'Comprar',
		donate: 'Doar',
		thanks: 'Recebemos sua doação. \nMuito Obrigado!',
		upgrade_message:
			'Você acaba de adquirir o plano Premium. \n Todas as funcionalidades deste aplicativo no plano Premium estão acessíveis.',
		congrats: 'Parabéns',
		upgrade_feature1: 'Adicionar mais de um caminhão',
		upgrade_feature2: 'Compartilhar registros mensais',
		upgrade_feature3: 'Compartilhar registros anuais',
		upgrade_feature4: 'Sem anúncios, exceto parcerias comerciais.',
		upgrade_title: 'Faça o upgrade da sua conta',
		upgrade_description:
			'Tenha todas as funcionalidades do aplicativo Fin Truck desbloqueadas. Ao assinar você terá 7 dias gráts para testar e pode cancelar quando quiser.',
		subscribe_monthly: 'Assinar plano mensal',
		subscribe_yearly: 'Assinar plano anual',
		unsubscribe: 'Cancelar Assinatura',
		warning: 'Aviso',
		connection_message:
			'Olá amigo, atualmente você está utilizando o aplicativo Fin Truck no plano Fremium. \n Nesse plano o uso do aplicativo é limitado. Para prosseguir você precisa assinar nosso aplicativo, o valor é simbólico, assim você nos ajuda a manter e a melhorar nosso serviço. \n Por favor, verifique se:',
		network_warning: 'Possui conexão com a Internt',
		play_store_warning: 'Está conectado com a PlayStore',
		apple_store_warning: 'Está conectado com a AppleStore',
		attention: 'Atenção',
		offline_message:
			'O aplicativo Fin Truck funciona offline, você precisa estar conectado apenas para assinar e fazer o upgrade para o plano Premium.',
	},
};
