export const monthsNames = {
	december: {
		'pt-BR': 'Dezembro',
		'en-US': 'December',
		es: 'Deciembre',
		order: 0,
		monthNumber: 11,
	},
	november: {
		'pt-BR': 'Novembro',
		'en-US': 'November',
		es: 'Noviembre',
		order: 1,
		monthNumber: 10,
	},
	october: {
		'pt-BR': 'Outubro',
		'en-US': 'October',
		es: 'Octubre',
		order: 2,
		monthNumber: 9,
	},
	september: {
		'pt-BR': 'Setembro',
		'en-US': 'September',
		es: 'Septiembre',
		order: 3,
		monthNumber: 8,
	},
	august: {
		'pt-BR': 'Agosto',
		'en-US': 'August',
		es: 'Agosto',
		order: 4,
		monthNumber: 7,
	},
	july: {
		'pt-BR': 'Julho',
		'en-US': 'July',
		es: 'Julio',
		order: 5,
		monthNumber: 6,
	},
	june: {
		'pt-BR': 'Junho',
		'en-US': 'June',
		es: 'Junio',
		order: 6,
		monthNumber: 5,
	},
	may: {
		'pt-BR': 'Maio',
		'en-US': 'May',
		es: 'Mayo',
		order: 7,
		monthNumber: 4,
	},
	april: {
		'pt-BR': 'Abril',
		'en-US': 'April',
		es: 'Abril',
		order: 8,
		monthNumber: 3,
	},
	march: {
		'pt-BR': 'Março',
		'en-US': 'March',
		es: 'Marzo',
		order: 9,
		monthNumber: 2,
	},
	february: {
		'pt-BR': 'Fevereiro',
		'en-US': 'February',
		es: 'Febrero',
		order: 10,
		monthNumber: 1,
	},
	january: {
		'pt-BR': 'Janeiro',
		'en-US': 'january',
		es: 'Enero',
		order: 11,
		monthNumber: 0,
	},
};
